"""
agents/ai_research/pdf_gen.py
Generates a nicely formatted PDF digest of AI research papers using fpdf2.
"""

import os
import textwrap
from datetime import datetime
from fpdf import FPDF, XPos, YPos


# Color palette
C_BG       = (248, 249, 250)
C_ACCENT   = (99,  102, 241)   # indigo
C_DARK     = (17,  24,  39)
C_MID      = (75,  85,  99)
C_LIGHT    = (156, 163, 175)
C_WHITE    = (255, 255, 255)
C_DIVIDER  = (229, 231, 235)
C_TAG_BG   = (238, 242, 255)


SOURCE_COLORS = {
    "HuggingFace Daily Papers": (255, 112,  0),
    "arXiv cs.LG":              (59,  130, 246),
    "arXiv cs.CL":              (16,  185, 129),
    "arXiv cs.AI":              (139,  92, 246),
    "OpenAI Blog":              (16,  163, 127),
    "Anthropic":                (205, 127,  50),
    "Google DeepMind":          (66,  133, 244),
    "Meta AI":                  (24, 119, 242),
}


class ResearchPDF(FPDF):
    def __init__(self, date_range: str):
        super().__init__()
        self.date_range = date_range
        self.set_auto_page_break(auto=True, margin=18)
        self.set_margins(18, 18, 18)

    def header(self):
        self.set_fill_color(*C_ACCENT)
        self.rect(0, 0, 210, 14, "F")
        self.set_y(3)
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*C_WHITE)
        self.cell(0, 8, "Homebody | AI Research Digest", align="L")
        self.set_font("Helvetica", "", 8)
        self.set_xy(0, 3)
        self.cell(0, 8, _safe(self.date_range), align="R")
        self.set_y(16)
        self.set_text_color(*C_DARK)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*C_LIGHT)
        self.cell(0, 6, f"Generated by Homebody AI  |  Page {self.page_no()}", align="C")


def _source_color(source: str) -> tuple:
    for key, color in SOURCE_COLORS.items():
        if key.lower() in source.lower():
            return color
    return C_ACCENT


def _safe(text: str) -> str:
    """Strip/replace characters outside Latin-1 range for Helvetica compatibility."""
    replacements = {
        "\u2013": "-", "\u2014": "-", "\u2018": "'", "\u2019": "'",
        "\u201c": '"', "\u201d": '"', "\u2026": "...", "\u00b7": "*",
        "\u2022": "*", "\u2192": "->", "\u2190": "<-", "\u00d7": "x",
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
    return text.encode("latin-1", errors="replace").decode("latin-1")


def _wrap(text: str, width: int = 90) -> str:
    return "\n".join(textwrap.wrap(text, width))


def generate_pdf(papers: list, output_path: str, date_range: str) -> str:
    """Generate PDF and return path."""
    # Sanitize everything for Latin-1 / Helvetica compatibility
    date_range = _safe(date_range)
    for p in papers:
        p.title    = _safe(p.title)
        p.authors  = _safe(p.authors)
        p.summary  = _safe(p.summary)
        p.source   = _safe(p.source)
        p.abstract = _safe(p.abstract)

    pdf = ResearchPDF(date_range)
    pdf.add_page()

    # ── Cover title block ──────────────────────────────────────────────────
    pdf.set_fill_color(*C_BG)
    pdf.rect(0, 14, 210, 28, "F")
    pdf.set_y(18)
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(*C_DARK)
    pdf.cell(0, 10, "AI Research Digest", align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*C_MID)
    pdf.cell(0, 6, f"{len(papers)} papers & posts  |  {date_range}", align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(4)

    # ── Source legend ──────────────────────────────────────────────────────
    sources = list(dict.fromkeys(p.source for p in papers))
    x = pdf.get_x()
    pdf.set_font("Helvetica", "", 7)
    for src in sources[:8]:
        col = _source_color(src)
        pdf.set_fill_color(*col)
        pdf.set_text_color(*C_WHITE)
        src = _safe(src)
        w = pdf.get_string_width(src) + 5
        if x + w > 190:
            x = 18
            pdf.ln(6)
        pdf.set_x(x)
        pdf.cell(w, 5, src, fill=True, new_x=XPos.RIGHT, new_y=YPos.TOP)
        x += w + 3
    pdf.ln(10)

    # ── Paper entries ───────────────────────────────────────────────────────
    for i, paper in enumerate(papers):
        y_before = pdf.get_y()

        # Source tag
        col = _source_color(paper.source)
        pdf.set_fill_color(*col)
        pdf.set_text_color(*C_WHITE)
        pdf.set_font("Helvetica", "B", 6.5)
        tag_w = pdf.get_string_width(paper.source) + 5
        pdf.cell(tag_w, 5, paper.source, fill=True)
        pdf.ln(6)

        # Title
        pdf.set_font("Helvetica", "B", 10.5)
        pdf.set_text_color(*C_DARK)
        title_lines = textwrap.wrap(paper.title, 85)
        for line in title_lines[:3]:
            pdf.cell(0, 5.5, line, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(1)

        # Authors (if present)
        if paper.authors:
            pdf.set_font("Helvetica", "I", 7.5)
            pdf.set_text_color(*C_LIGHT)
            authors_short = paper.authors[:100] + ("..." if len(paper.authors) > 100 else "")
            pdf.cell(0, 4, authors_short, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.ln(1)

        # Summary
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*C_MID)
        summary = paper.summary or paper.abstract or ""
        wrapped = textwrap.wrap(summary, 92)
        for line in wrapped[:6]:
            pdf.cell(0, 4.5, line, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(2)

        # Link
        pdf.set_font("Helvetica", "U", 8)
        pdf.set_text_color(*C_ACCENT)
        link_text = paper.url[:90] + ("..." if len(paper.url) > 90 else "")
        pdf.cell(0, 4, link_text, link=paper.url, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        # Divider
        pdf.ln(3)
        pdf.set_draw_color(*C_DIVIDER)
        pdf.line(18, pdf.get_y(), 192, pdf.get_y())
        pdf.ln(4)

    pdf.output(output_path)
    return output_path
