"""
agents/earnings_analyst/pdf_gen.py
Composes the earnings analyst PDF — chart-heavy, minimal text, dark-mode design.
"""

import textwrap
from datetime import datetime
from pathlib import Path
from fpdf import FPDF, XPos, YPos


def _s(text: str) -> str:
    """Sanitize to Latin-1."""
    replacements = {"\u2013":"-","\u2014":"-","\u2018":"'","\u2019":"'",
                    "\u201c":'"',"\u201d":'"',"\u2026":"...","\u2022":"*",
                    "\u2192":"->","\u00d7":"x","\u00ae":"(R)","\u2122":"(TM)"}
    for k, v in replacements.items():
        text = text.replace(k, v)
    return text.encode("latin-1", errors="replace").decode("latin-1")


C_BG       = (15,  17,  23)
C_SURFACE  = (26,  29,  39)
C_ACCENT   = (79, 142, 247)
C_GREEN    = (34, 197,  94)
C_RED      = (239, 68,  68)
C_TEXT     = (226, 232, 240)
C_SUBTEXT  = (148, 163, 184)
C_DIVIDER  = (45,  49,  72)
C_WHITE    = (255, 255, 255)


class EarningsPDF(FPDF):
    def __init__(self, company: str, ticker: str, date_str: str):
        super().__init__()
        self.company  = company
        self.ticker   = ticker
        self.date_str = date_str
        self.set_auto_page_break(auto=True, margin=14)
        self.set_margins(14, 14, 14)

    def header(self):
        self.set_fill_color(*C_BG)
        self.rect(0, 0, 210, 210, "F")   # full page dark bg
        self.set_fill_color(*C_ACCENT)
        self.rect(0, 0, 210, 11, "F")
        self.set_y(2.5)
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*C_WHITE)
        self.cell(0, 6, f"EARNINGS ANALYST  |  {_s(self.company)} ({self.ticker})", align="L")
        self.cell(0, 6, self.date_str, align="R")
        self.set_y(13)

    def footer(self):
        self.set_y(-10)
        self.set_font("Helvetica", "I", 6)
        self.set_text_color(*C_SUBTEXT)
        self.cell(0, 5, f"Page {self.page_no()}  |  Data: Yahoo Finance  |  Generated by Homebody AI", align="C")


def _metric_box(pdf, label: str, value: str, color: tuple, x: float, y: float, w=42, h=16):
    pdf.set_fill_color(*C_SURFACE)
    pdf.rect(x, y, w, h, "F")
    pdf.set_fill_color(*color)
    pdf.rect(x, y, 2, h, "F")          # left accent stripe
    pdf.set_xy(x + 3, y + 2)
    pdf.set_font("Helvetica", "", 6)
    pdf.set_text_color(*C_SUBTEXT)
    pdf.cell(w - 4, 4, _s(label), new_x=XPos.LEFT, new_y=YPos.NEXT)
    pdf.set_x(x + 3)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*C_TEXT)
    pdf.cell(w - 4, 7, _s(value))


def _section_title(pdf, title: str):
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(*C_ACCENT)
    pdf.cell(0, 6, _s(title).upper(), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_draw_color(*C_ACCENT)
    pdf.line(14, pdf.get_y(), 196, pdf.get_y())
    pdf.ln(3)


def _fmt(val, scale=1e9, suffix="B"):
    if val is None: return "N/A"
    return f"${val/scale:.1f}{suffix}"


def generate(data: dict, chart_paths: dict, sentiment_data: list,
             llm_summary: str, output_path: str) -> str:

    company = data["company_name"]
    ticker  = data["ticker"]
    now     = datetime.now().strftime("%b %d, %Y")
    quarters = data["quarters"]
    latest   = quarters[0] if quarters else {}

    pdf = EarningsPDF(company, ticker, now)

    # ── PAGE 1: Summary dashboard ─────────────────────────────────────────────
    pdf.add_page()
    pdf.ln(2)

    # Company name
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(*C_TEXT)
    pdf.cell(0, 10, _s(company), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(*C_SUBTEXT)
    pdf.cell(0, 5, f"{_s(data.get('sector',''))}  |  {_s(data.get('industry',''))}  |  {ticker}",
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(4)

    # Key metric boxes
    cap = data.get("market_cap")
    cap_str = _fmt(cap, 1e12, "T") if cap and cap > 1e12 else _fmt(cap, 1e9, "B")
    metrics = [
        ("Market Cap",      cap_str,                                        C_ACCENT),
        ("Latest Revenue",  _fmt(latest.get("revenue"), 1e9, "B"),         C_GREEN),
        ("Gross Margin",    f"{latest.get('gross_margin', 0) or 0:.1f}%",  C_GREEN if (latest.get("gross_margin") or 0) > 40 else C_SUBTEXT),
        ("Op. Margin",      f"{latest.get('op_margin', 0) or 0:.1f}%",    C_GREEN if (latest.get("op_margin") or 0) > 10 else C_RED),
        ("Free Cash Flow",  _fmt(latest.get("fcf"), 1e9, "B"),             C_GREEN if (latest.get("fcf") or 0) > 0 else C_RED),
    ]
    start_x = 14
    for i, (label, val, color) in enumerate(metrics):
        _metric_box(pdf, label, val, color, start_x + i * 37, pdf.get_y(), w=36)
    pdf.ln(22)

    # LLM summary (short)
    if llm_summary:
        pdf.set_font("Helvetica", "", 7.5)
        pdf.set_text_color(*C_TEXT)
        for line in textwrap.wrap(_s(llm_summary), 96)[:4]:
            pdf.cell(0, 4.5, line, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(5)

    # Revenue chart
    if chart_paths.get("revenue"):
        _section_title(pdf, "Revenue & Growth")
        pdf.image(chart_paths["revenue"], x=14, w=88)
        pdf.ln(3)

    # Margins chart
    if chart_paths.get("margins"):
        _section_title(pdf, "Margin Trends")
        pdf.image(chart_paths["margins"], x=14, w=88)
        pdf.ln(3)

    # ── PAGE 2: EPS + Income + FCF + Stock ────────────────────────────────────
    pdf.add_page()
    pdf.ln(2)

    if chart_paths.get("eps"):
        _section_title(pdf, "EPS: Actual vs Estimate + Surprise")
        pdf.image(chart_paths["eps"], x=14, w=88)
        pdf.ln(4)

    if chart_paths.get("income_fcf"):
        _section_title(pdf, "Operating Income & Free Cash Flow")
        pdf.image(chart_paths["income_fcf"], x=14, w=110)
        pdf.ln(4)

    if chart_paths.get("stock"):
        _section_title(pdf, "12-Month Stock Performance")
        pdf.image(chart_paths["stock"], x=14, w=100)
        pdf.ln(4)

    # ── PAGE 3: Sentiment + News ──────────────────────────────────────────────
    if chart_paths.get("sentiment"):
        pdf.add_page()
        pdf.ln(2)
        _section_title(pdf, "Earnings Call Sentiment (AI Scored)")
        pdf.image(chart_paths["sentiment"], x=14, w=100)
        pdf.ln(4)

        # Sentiment notes
        for s in sentiment_data:
            pdf.set_font("Helvetica", "B", 7)
            pdf.set_text_color(*C_ACCENT)
            pdf.cell(30, 4.5, _s(s["label"]))
            pdf.set_font("Helvetica", "", 7)
            pdf.set_text_color(*C_TEXT)
            score_color = C_GREEN if s["score"] >= 0.6 else (C_RED if s["score"] < 0.4 else C_SUBTEXT)
            pdf.set_text_color(*score_color)
            pdf.cell(25, 4.5, f"{s['tone']} ({s['score']:.2f})")
            pdf.set_text_color(*C_SUBTEXT)
            pdf.cell(0, 4.5, _s(s.get("note", "")), new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        # News
        pdf.ln(5)
        _section_title(pdf, "Recent News Headlines")
        pdf.set_font("Helvetica", "", 7)
        pdf.set_text_color(*C_SUBTEXT)
        for headline in data.get("news", [])[:8]:
            if headline:
                pdf.cell(4, 4.5, "-")
                for line in textwrap.wrap(_s(headline), 92)[:2]:
                    pdf.cell(0, 4.5, line, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.output(output_path)
    return output_path
